style: github
template: CHANGELOG.tpl.md
info:
  title: SteamLauncher CHANGELOG
  repository_url: https://github.com/Sak32009/SteamLauncher
options:
  commits:
    filters:
      Type:
        - fix
        - feat
        - build
        - chore
        - ci
        - docs
        - style
        - refactor
        - perf
        - test
    sort_by: Type
  commit_groups:
    title_maps:
      fix: Bug Fixes
      feat: Features
      build: Build
      chore: Chore
      ci: CI
      docs: Docs
      style: Style
      refactor: Code Refactoring
      perf: Performance Improvements
      test: Test
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
